const catalogBlocksList = [
    {
        title: 'Martin',
        text: 'Мягкое кресло «Альба» компании «Экми -мебель»- это украшение и удобное дополнение Вашего интерьера. Кресло «Альба» оптимальная личная зона для отдыха.',
        img: './src/assets/img/products/Martin.png',
        id: 1,
        type: 'Sofa',
    },
    {
        title: 'Alba',
        text: 'Мягкое кресло «Альба» компании «Экми -мебель»- это украшение и удобное дополнение Вашего интерьера. Кресло «Альба» оптимальная личная зона для отдыха.',
        img: './src/assets/img/products/Alba.png',
        id: 2,
        type: 'Armchair',
    },
    {
        title: 'Toscana',
        text: 'Кресло «Тоскана» компании «EKMI-мебель». Располагает для удобного времяпровождения.',
        img: './src/assets/img/products/Toscana.png',
        id: 3,
        type: 'Armchair',
    },
    {
        title: 'Leonardo',
        text: 'Мягкое кресло «Альба» компании «Экми -мебель»- это украшение и удобное дополнение Вашего интерьера. Кресло «Альба» оптимальная личная зона для отдыха.',
        img: './src/assets/img/products/Leonardo.png',
        id: 4,
        type: 'Sofa',
    },
    {
        title: 'Boorbon',
        text: 'Кресло «Тоскана» компании «EKMI-мебель». Располагает для удобного времяпровождения.',
        img: './src/assets/img/products/Boorbon.png',
        id: 5,
        type: 'Sofa',
    },
    {
        title: 'Emilio',
        text: 'Легкий, воздушный, невесомый… Диван «Арни», непроизвольно вызывающий ассоциацию с облаком,  буквально излучает уют. Объёмные  модули легко комбинируются между собой, создавая любимое место отдыха для всей семьи. Композиция может быть дополнена креслами и пуфами.',
        img: './src/assets/img/products/Emilio.png',
        id: 6,
        type: 'Sofa',
    },
    {
        title: 'Nensi',
        text: 'Мягкие формы кровати «Ненси» создадут уют и комфорт в Вашей спальне.',
        img: './src/assets/img/products/Nensi.png',
        id: 7,
        type: 'Bed',
    },
    {
        title: 'Tatami',
        text: 'Легкий, воздушный, невесомый… Диван «Арни», непроизвольно вызывающий ассоциацию с облаком,  буквально излучает уют. Объёмные  модули легко комбинируются между собой, создавая любимое место отдыха для всей семьи. Композиция может быть дополнена креслами и пуфами. ',
        img: './src/assets/img/products/Tatami.png',
        id: 8,
        type: 'Sofa',
    },
    {
        title: 'Regina',
        text: 'Легкий, воздушный, невесомый… Диван «Арни», непроизвольно вызывающий ассоциацию с облаком,  буквально излучает уют. Объёмные  модули легко комбинируются между собой, создавая любимое место отдыха для всей семьи. Композиция может быть дополнена креслами и пуфами.',
        img: './src/assets/img/products/Regina.png',
        id: 9,
        type: 'Sofa',
    },
    {
        title: 'Malta',
        text: 'Двусторонний матрац МАЛЬТА без пружин – удачное сочетание жестокости и комфортности. Самый низкий матрац в нашей линейке.',
        img: './src/assets/img/products/Malta.png',
        id: 10,
        type: 'Mattress',
    },
    {
        title: 'Versal',
        text: 'Мягкие формы кровати «Ненси» создадут уют и комфорт в Вашей спальне.',
        img: './src/assets/img/products/Versal.png',
        id: 11,
        type: ['Chair','Poof'],
    },
    {
        title: 'Exclusive 1',
        text: 'Мягкие формы кровати «Ненси» создадут уют и комфорт в Вашей спальне.',
        img: './src/assets/img/products/Exclusive 1.png',
        id: 12,
        type: ['Sofa', 'Exclusive'],
    },
    {
        title: 'Floret',
        text: 'Легкий, воздушный, невесомый… Диван «Арни», непроизвольно вызывающий ассоциацию с облаком,  буквально излучает уют. Объёмные  модули легко комбинируются между собой, создавая любимое место отдыха для всей семьи. Композиция может быть дополнена креслами и пуфами.',
        img: './src/assets/img/products/Floret.png',
        id: 13,
        type: 'Sofa',
    },
    {
        title: 'Exclusive bed 2',
        text: 'Эксклюзивная мебель',
        img: './src/assets/img/products/Exclusive bed 2.png',
        id: 14,
        type: ['Bed', 'Exclusive'],
    },
    {
        title: 'Arni',
        text: 'Легкий, воздушный, невесомый… Диван «Арни», непроизвольно вызывающий ассоциацию с облаком,  буквально излучает уют. Объёмные  модули легко комбинируются между собой, создавая любимое место отдыха для всей семьи. Композиция может быть дополнена креслами и пуфами.',
        img: './src/assets/img/products/Arni.png',
        id: 15,
        type: 'Sofa',
    },
    {
        title: 'Taiti',
        text: 'Эксклюзивный матрац с ортопедическим эффектом без пружин. Самая жесткая, но при этом очень комфортная модель во всей линейке. Идеальный вариант для крупных людей.',
        img: './src/assets/img/products/Taiti.png',
        id: 16,
        type: 'Mattress',
    },
    {
        title: '1',
        text: '1',
        img: './src/assets/img/logo.svg',
        id: 17,
        type: 'Mattress',
    },
    {
        title: '1',
        text: '1',
        img: './src/assets/img/logo.svg',
        id: 18,
        type: 'Mattress',
    },
    {
        title: '1',
        text: '1',
        img: './src/assets/img/logo.svg',
        id: 19,
        type: 'Mattress',
    },
    {
        title: '1',
        text: '1',
        img: './src/assets/img/logo.svg',
        id: 20,
        type: 'Mattress',
    },
    {
        title: '1',
        text: '1',
        img: './src/assets/img/logo.svg',
        id: 21,
        type: 'Mattress',
    },
    {
        title: '1',
        text: '1',
        img: './src/assets/img/logo.svg',
        id: 22,
        type: 'Mattress',
    },
    {
        title: '1',
        text: '1',
        img: './src/assets/img/logo.svg',
        id: 23,
        type: 'Mattress',
    },
    {
        title: '1',
        text: '1',
        img: './src/assets/img/logo.svg',
        id: 24,
        type: 'Mattress',
    },
    {
        title: '1',
        text: '1',
        img: './src/assets/img/logo.svg',
        id: 25,
        type: 'Mattress',
    },
    {
        title: '1',
        text: '1',
        img: './src/assets/img/logo.svg',
        id: 26,
        type: 'Mattress',
    },
    {
        title: '1',
        text: '1',
        img: './src/assets/img/logo.svg',
        id: 27,
        type: 'Mattress',
    },
    {
        title: '1',
        text: '1',
        img: './src/assets/img/logo.svg',
        id: 28,
        type: 'Mattress',
    },
    {
        title: '1',
        text: '1',
        img: './src/assets/img/logo.svg',
        id: 29,
        type: 'Mattress',
    },
    {
        title: '1',
        text: '1',
        img: './src/assets/img/logo.svg',
        id: 30,
        type: 'Mattress',
    },
    {
        title: '1',
        text: '1',
        img: './src/assets/img/logo.svg',
        id: 31,
        type: 'Mattress',
    },
    {
        title: '1',
        text: '1',
        img: './src/assets/img/logo.svg',
        id: 32,
        type: 'Mattress',
    },
    {
        title: '1',
        text: '1',
        img: './src/assets/img/logo.svg',
        id: 33,
        type: 'Mattress',
    },
];

export default catalogBlocksList;